### PR TITLE
[WIP] Add Opsworks

### PR DESCRIPTION
**Pull request by cmcarthur**
@dtan4 I added this so we could use opsworks thru terraforming. It works well, but I'd like to get stylistic feedback from you before I continue.

TODO:

- [ ] Write Opsworks spec

### CODE REVIEW

**Comment by dtan4** [comment]
I added `[WIP]` to PR title. Please remove this when this PR becomes ready to merge.

**Comment by dtan4** [comment]
I will review this in a day or two :eyes: :bow:

**Comment by aibou** [comment]
:+1:

**Comment by dtan4** [comment]
Sorry for being late :bow: 

It seems that your patch generates _multiple_ Opsworks resources (`aws_opsworks_stack `, `aws_opsworks_custom_layer `) at once. However I'd like to  keep Terraforming command and generated resource one-to-one. So `opsworks` command should be divided into separate resources.

- `$ terraforming opws` => `aws_opsworks_stack`
- `$ terraforming opwcl` => `aws_opsworks_custom_layer`

**Comment by cmcarthur** [comment]
@dtan4 Ok, thanks. I'll split those up into separate resources, and get to work on writing specs in a few days.

**Comment by dtan4** [comment]
@cmcarthur Is there any update?

**Pull request merged**
