### PR TITLE
CloudFrontDistribution resource

### PR DESCRIPTION
**Pull request by szemek**
This pull request is more like a good start than complete implementation of CloudFrontDistribution resource.
I'm adding this resource under `cfd` subcommand.

I appreciate any feedback on that.

### CODE REVIEW

**Comment by ehershey** [comment]
FWIW I used this successfully to tee up some cloudfront distribution tf configs from existing resources.  It worked pretty well overall. I noticed a while later that it had ignored custom error responses on the resources I was basing new distributions on.

**Comment by Sveder** [comment]
Also tried it out and same experience as @ehershey - worked but without custom error responses.

**Comment by lsamuels-fearless** [comment]
When I recently used this branch to pull my cloudfront distributions states the resulting terraform state file was invalid because the boolean values in the attributes blocks did not have quotes around them. Relevant attributes:
**enabled
is_ipv6_enabled**

**Comment by jamesarosen** [comment]
It might be nice to sort by `id`, which is what the S3 importer does:
```erb
distributions.sort_by(&:id).each…
```

**Comment by al73rna** [comment]
Nice work! I also used this to export a distribution. It missed the custom `origin_path` for my s3 bucket. other than that, everything seems to be fine.

**Review by amoldabade7 — APPROVED** [review]

**Comment by AlysiaWu** [comment]
I wonder when this PR can be merged and released? this feature will be pretty helpful to have 👍

**Pull request closed without merging**
