### PR TITLE
[WIP] Add DynamoDB support

### PR DESCRIPTION
**Pull request by potsbo**
## WHY

from https://github.com/dtan4/terraforming/issues/288
As mentioned, we want DynamoDB support.

## WHAT

Implement DynamoDB support.

### Tasks
- [x] Implement rest of arguments
  - [x] stream_enabled
  - [x] stream_view_type
  - [x] local_secondary_index
  - ref https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html
- [ ] Implement tfstate support
- [ ] Write tests
- [ ] Update Readme to show DynamoDB is supported

## WHAT TO DISCUS
@dtan4 I want to make sure my approach to implement this is ok for this project.
And also, how do you think about the abbreviation `dynm`.

### CODE REVIEW

**Comment by dtan4** [comment]
> And also, how do you think about the abbreviation dynm.

`ddb` is more suitable.

### Google Search Result

- [`DynamoDB "dynm"`](https://www.google.co.jp/search?client=ubuntu&channel=fs&q=dynamodb+%22ddb%22&ie=utf-8&oe=utf-8&hl=ja#channel=fs&hl=ja&q=dynamodb+%22dynm%22)
  - 2 results
- [`DynamoDB "ddb"`](https://www.google.co.jp/search?client=ubuntu&channel=fs&q=dynamodb+%22ddb%22&ie=utf-8&oe=utf-8&hl=ja)
  - approx. 8010 results

**Comment by dtan4** [comment]
> I want to make sure my approach to implement this is ok for this project.

It looks good now. Please follow [contribution guide](https://github.com/dtan4/terraforming/blob/master/CONTRIBUTING.md#adding-new-resource).

**Comment by potsbo** [comment]
Decided to use 'ddb'

**Comment by potsbo** [comment]
@dtan4 I'm about to write specs, which seems to be very though to do.
Do you have any tips to write spec easily?

**Comment by dtan4** [comment]
## expected tf / tfstate

Create new resource with Terraform actually, then check your `.tf` and generated `terraform.tfstate`.

## Stub of AWS API call

After creating real resource, run API on irb/pry, then copy result.

```ruby
client = Aws::DynamoDB::Client.new
tables = client.list_tables # or something else
tables.to_h # copy the result
```

**Comment by sulaimanismail** [comment]
I have followed the exact workaround but I still getting the error when I run,
$ terraforming dynamo_db
Could not find command "dynamo_db".

is there any recommendation.

**Comment by potsbo** [comment]
Closing this PR, because it seems [Add Dynamo DB support by laxmiprasanna-gunna · Pull Request #440 · dtan4/terraforming](https://github.com/dtan4/terraforming/pull/440) is better than this PR.

Hi @sulaimanismail, I don't know what you are trying to do and what you have done.
But I suppose that the pr above is the better example to do.

**Pull request closed without merging**
