### PR TITLE
Added handling of access_logs for ELB

### PR DESCRIPTION
**Pull request by ranrub**

### CODE REVIEW

**Comment by dtan4** [comment]
Please update specs together :bow: 
:point_right: [spec/lib/terraforming/resource/elb_spec.rb](https://github.com/dtan4/terraforming/blob/master/spec/lib/terraforming/resource/elb_spec.rb)

**Comment by dtan4** [comment]
@ranrub  Is there any update?

**Comment by ranrub** [comment]
Hi Daisuke

I'm sorry but I don't have available time to write these tests. If you want
to write them I don't mind of course.

Ran

**Comment by dtan4** [comment]
ELB `access_logs` support was implemented at https://github.com/dtan4/terraforming/pull/223.
Thank you for sending Pull Request, and please use the latest Terraforming.

**Pull request closed without merging**
